# permissions for end users to edit definitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: devcontainer
    app.kubernetes.io/managed-by: kustomize
  name: definition-editor-role
rules:
- apiGroups:
  - devcontainer.everproc.com
  resources:
  - definitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devcontainer.everproc.com
  resources:
  - definitions/status
  verbs:
  - get
