apiVersion: devcontainer.everproc.com/v1alpha1
kind: Workspace
metadata:
  labels:
    app.kubernetes.io/name: devcontainer
    app.kubernetes.io/managed-by: kustomize
  name: workspace-sample
spec:
  owner: john
  gitHashOrTag: master
  gitUrl: "https://github.com/daemonfire300/sample-jupyter-devcontainer.git"
  containerRegistry: "kind-registry:5000"
  insecureContainerRegistry: "true"
