apiVersion: devcontainer.everproc.com/v1alpha1
kind: Definition
metadata:
  labels:
    app.kubernetes.io/name: devcontainer
    app.kubernetes.io/managed-by: kustomize
  name: my-definition-sample
spec:
  # TODO(user): Add fields here
  source: private-template-starter
  gitHashOrTag: main
  storageClassName: openebs-rwx
